# Generated by Django 4.1.2 on 2022-10-29 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anggota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nia', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'jemaat',
                'verbose_name_plural': 'jemaat',
                'db_table': 'anggota',
            },
        ),
        migrations.CreateModel(
            name='Wilayah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Wilayah',
                'verbose_name_plural': 'Wilayah',
                'db_table': 'wilayah',
            },
        ),
        migrations.CreateModel(
            name='Pengusul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('penatua_alasan_1', models.TextField(blank=True, null=True)),
                ('penatua_alasan_2', models.TextField(blank=True, null=True)),
                ('penatua_alasan_3', models.TextField(blank=True, null=True)),
                ('penatua_alasan_4', models.TextField(blank=True, null=True)),
                ('penatua_alasan_5', models.TextField(blank=True, null=True)),
                ('konfirmasi', models.BooleanField(default=False)),
                ('anggota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengusul', to='anggota.anggota', verbose_name='Anggota')),
                ('penatua_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penatua_alasan_1', to='anggota.anggota', verbose_name='Usulan Penatua Pertama')),
                ('penatua_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='penatua_alasan_2', to='anggota.anggota', verbose_name='Usulan Penatua Kedua')),
                ('penatua_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='penatua_alasan_3', to='anggota.anggota', verbose_name='Usulan Penatua Ketiga')),
                ('penatua_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='penatua_alasan_4', to='anggota.anggota', verbose_name='Usulan Penatua Keempat')),
                ('penatua_5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='penatua_alasan_5', to='anggota.anggota', verbose_name='Usulan Penatua Kelima')),
            ],
            options={
                'verbose_name': 'pengusul',
                'verbose_name_plural': 'pengusul',
                'db_table': 'pengusul',
            },
        ),
        migrations.AddField(
            model_name='anggota',
            name='wilayah',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anggota.wilayah'),
        ),
    ]
