# Generated by Django 3.2.16 on 2022-10-30 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anggota', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengusul',
            name='penatua_mobile_1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pengusul',
            name='penatua_mobile_2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pengusul',
            name='penatua_mobile_3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pengusul',
            name='penatua_mobile_4',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pengusul',
            name='penatua_mobile_5',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
